### ISSUE TITLE
iSpindel (Aux) Temp not displayed correctly

### ISSUE THREAD

**Issue by lekrom** [vitotai/BrewPiLess#12]
Dear @vitotai 

I stumbled upon a small bug. The iSpindel (Aux) temperature is not correctly displayed on my BPL (chart or legend). I setup BPL (in STA-mode) with static IP and setup iSpindel to match. I also setup remote logging (of all available variables) to ubidots. The aux temperature is always displayed as 17.53 (does not change) in BPL. Funny enough, its correctly displayed on my ubidots dashboard. Therefore, I expect it is bug in the display, not the comms.So far, everything else seems to display fine, I have not hooked up the DS18B20's yet (still in the mail).

Regards,
Lekrom

**Comment by vitotai** [comment]
Hi,
Maybe something goes wrong, I will check this issue later.
Mine is like this:
![auxtemp](https://user-images.githubusercontent.com/15953213/27497128-eb4542ac-580d-11e7-9cab-a8cc892c2374.jpg)

It does change in a weird way.

**Comment by lekrom** [comment]
Ok. Thanks for the reply. Great work BTW...

**Comment by vitotai** [comment]
I found the bug. It is a stupid but common mistake by using "&&" when it should be "&".
I will fix it shortly.

**Comment by lekrom** [comment]
Great, Thanks, I have made a few of those types of mistakes... I will try it out tonight.

**Comment by lekrom** [comment]
Thanks @vitotai , appears to be working correctly.
