### ISSUE TITLE
Secondary Web Interface (How To)

### ISSUE THREAD

**Issue by dotps1** [vitotai/BrewPiLess#130]
I read (at some point) there was a secondary refactored web interface that someone had created, is there any how to's on how to set it up?  I read it was committed to this repo (I think).  thanks!

**Comment by vitotai** [comment]
Download 
index.htm.gz, config.htm.gz, gravity.htm.gz, logging.htm.gz, setup.htm.gz, control.htm.gz
from the following folder:
https://github.com/vitotai/BrewPiLess/tree/master/htmljs/dist

open filemanager
http://brewpiless.local:8008/filemanager

upload the downloaded files. Don't forget to "reload" the pages.

**Comment by dotps1** [comment]
extract them first?

**Comment by vitotai** [comment]
No extraction. Use exact what they are named.

**Comment by dotps1** [comment]
worked good, thanks.

**Comment by vitotai** [comment]
yes. You can delete them, and the embedded files will be used.

**Comment by dotps1** [comment]
forgive me, but I did not see a delete option in the file manager page.  only upload and create.

**Comment by allthepies** [comment]
Right click on the file you want to delete, you should then get a popup menu with a delete option.

**Comment by dotps1** [comment]
I feel like I tried that as well, however I will attempt it again when I get home.  Thanks!

**Comment by dotps1** [comment]
yeah, right click doesn't do anything, using Firefox.
