### ISSUE TITLE
Onewire temperature  sensor issue

### ISSUE THREAD

**Issue by FluxFace** [vitotai/BrewPiLess#132]
I have build an BPL and having problem with the temperature sensors.
When i connect one DS18B20 onewire sensor to BPL it shows up in BPL and works fine.
If i connect two DS18B20 BPL won´t find the sensors. What am i doing wrong her?

**Comment by allthepies** [comment]
How are you connecting them ?  Bus style (as per the diagram link) ?
Do you have a 4K7 resistor between the data line and VCC ?
What voltage is VCC ?

https://cdn.instructables.com/F79/RUWE/GTUY9ZXQ/F79RUWEGTUY9ZXQ.LARGE.jpg

**Comment by FluxFace** [comment]
Connecting them like the diagram you linked to. Yes i have a 4K7 resistor between the data line and VCC. The voltage is 3.3v I have tried with 5v  The strange is that it works with one sensor but not two.
I have tried to flash with V3 and upload with platformIO

**Comment by FluxFace** [comment]
I have found the problem. It was a bad resistor.
Thank you for the help.
