### ISSUE TITLE
brewpiless.local/lcd not working

### ISSUE THREAD

**Issue by flo269** [vitotai/BrewPiLess#134]
Hi,

I updated to 3.2 yesterday and all works as expected, apart from brewpiless.local/lcd.
I also tried $ipaddress/lcd and tried with firefox, chrome and safari - without success.

In firefox I get the following messages on the developer console:

<img width="1279" alt="screenshot 2018-10-14 at 12 36 12" src="https://user-images.githubusercontent.com/25147331/46915589-e8fd3400-cfad-11e8-9e50-4033c6db238a.png">

If there's anything I can do to help, let me know.

Cheers
Flo

**Comment by vitotai** [comment]
I am sorry. Thinking nobody uses that, I removed the file.

You can upload the lcd.htm.gz by using http://[ipaddress]:8008/filemanager
https://github.com/vitotai/BrewPiLess/tree/master/extra

And access it as 
http://[ipaddress]/lcd.htm
