### ISSUE TITLE
Multi languages - portuguese

### ISSUE THREAD

**Issue by gumazza** [vitotai/BrewPiLess#139]
Vito, I translated and created a new portuguesbr.json file. As I'm not a programmer, I can not use grunt or create the "data" files. Do you have an instruction to provide, so you can create the appropriate files?

**Comment by vitotai** [comment]
It's a little complicated even to me.
You will have to setup node.js environment, download the htmljs directory, install some module when necessary, and then build the code.

https://github.com/vitotai/BrewPiLess/tree/master/htmljs

If you want to make them embedded, an extra step is needed to create the header files. That is the "output.sh" in htmljs subfolder, which is a shell script that runs under Mac OSX.

Or, you can attach the file here after finishing translation. I can build it for you.

**Comment by gumazza** [comment]
I'm learning to play Github, I do not know if I did it correctly, I'm sorry for that.
At the moment I prefer you to do this conversion, so I'm sending the link of the changed code.
Guess what I need, please.

https://github.com/gumazza/BrewPiLess/blob/master/portuguesbr.json

**Comment by gumazza** [comment]
Hi, Vito.
I am able to generate the translated HTMLs, now I am trying to generate the files that go to the ESP.
Disregard for now the translated file that you send, the "portuguesbr.json".
I will attach to my git, the new .json and the generated HMTLs, so I check everything and have total certainty.

Thank you for now.

**Comment by vitotai** [comment]
Check this branch out:
https://github.com/vitotai/BrewPiLess/tree/portuguesbr

**Comment by gumazza** [comment]
Here are all the files I was able to generate.
A check was made and the translation had to be updated to get a better interpretation.
https://github.com/gumazza/BrewPiLess

Thanks.

**Comment by vitotai** [comment]
updated.

**Comment by gumazza** [comment]
We are working on the translation, there is still a point that we are studying to improve.
Thanks for now, I'll send you the final version.

**Comment by moscabeer** [comment]
Is it possible to change the lcd screen language?

**Comment by gumazza** [comment]
Tanks Vito.

I will try these updates and send you the translated DisplayLCD.cpp here.
