### ISSUE TITLE
192.168.4.1 I can not access

### ISSUE THREAD

**Issue by moscabeer** [vitotai/BrewPiLess#140]
I installed version 3.2. it normally enters my network, it is in the ap-station mode. I use it in my house and also use it in a friend's house, when I use it in his house, I can not access 192.168.1.4 to change the network. it enters the brewpiless network, but then it disconnects.
I've tested several wemos d1mini. using the brewmaniac it works, but with brewpiless it's giving that problem.
do you have any way to reset it to go back to the initial settings? without using the platformIO, because I do not know how to use it. I always install through the .bin file.

**Comment by vitotai** [comment]
First of all, the IP address of SoftAP should be 192.168.4.1.

What browser are you using?

**Comment by moscabeer** [comment]
0Sorry, I meant 192.168.4.1
I'm using chrome, by smartfhone android.

**Comment by moscabeer** [comment]
https://youtu.be/hR_gHSj-a5s


see the video

**Comment by vitotai** [comment]
I don't have any android phone to test this issue.
Please use regular computer and open debug console to get the debug messages, if possible.

**Comment by LucLN** [comment]
Hi,

for me almost the same on iOS and Linux ..

The connection to 192.168.4.1 works if I'm on Brewpiless's wifi,

but no connection if connected to my regular wifi ..

Luc.

**Comment by amlynarczyk** [comment]
It's obvious. When you are on your regular wifi, the IP of brewpiless is different, you should probably check it on your access point, if you are using dhcp for that.

If you are on iOS device, you can also try connecting to http://brewpiless.local if you are on regular wifi.

**Comment by LucLN** [comment]
of course .. so I start at the big bang ..

1) iOS or Linux connected to Brewpiless-AP, get 192.168.4.2 as it's IP-address and is able to connect to 192.168.4.1 and display Brewpiless's webpage

2) iOS connected to my regular wifi with  192.168.0.10 as its ip-address , Brewpiless connected also to my regular wifi with 192.168.0.20 as its ip-address ..  NO  access to Brewpiless's webpage at 192.168.0.20

I tried with a fresh ESP8266 which gives me the same behavior. The only version that actually works for me is 3.0r2 and below. Everything from 3.1 upwards shows the same problem ..

iOS = a device running Apple's iOS, like an iPhone or iPad and Safari or Firefox as a browser

Linux = a PC running the Linux opperating-system

Does anyone has the same behavior ?

**Comment by amlynarczyk** [comment]
On version 3.1 version of brewpiless with old ui was also using Legacy ESP Async Lib, which made it not work properly on node mcu etc.

You can try installing 3.1 newui version and it should fix the issue.

New versions from what I see are always using new library, so they should work. At least looking at current platform.ini file.

**Comment by moscabeer** [comment]
> Não tenho telefone Android para testar esse problema. 
> Por favor, use o computador normal e abra o console de depuração para obter as mensagens de depuração, se possível.

I'm very lazy on this subject, I did not understand what I meant by debugging, and I do not know how to do that.
I could not solve it, I installed version 3.1 in Spanish and now it's good. Then I'll install 3.3.

**Comment by moscabeer** [comment]
Is it possible to change the lcd screen language?

**Comment by moscabeer** [comment]
> I don't have any android phone to test this issue.
> Please use regular computer and open debug console to get the debug messages, if possible.

I'm very lazy on this subject, I did not understand what I meant by debugging, and I do not know how to do that.
I could not solve it, I installed version 3.1 in Spanish and now it's good. Then I'll install 3.3.

**Comment by moscabeer** [comment]
vitotai
I installed version 3.4 in Portuguese, success, now I can enter in AP mode. Thanks for the great service.
