### ISSUE TITLE
Lowering heating time to stop cycling

### ISSUE THREAD

**Issue by quimnut** [vitotai/BrewPiLess#15]
I'm getting some hot/cold cycling because the heat cycle will lift my temp .5c 
Can the minimum duration be lowered? 
I have a heat band around a ss brew bucket.

I would the get same effect with cooling if my chamber sensor is not under the fridge element, but with heating it's not easy to resolve like that.

![my temp](http://i.imgur.com/nFMFm7b.png)

**Comment by vitotai** [comment]
You can try this branch:
https://github.com/vitotai/BrewPiLess/tree/v22platformio

If you are using glycol, it's perfect for you.
Check the readme carefully, and report back. Thanks.

**Comment by tommueller** [comment]
couldn't you use the PID library https://github.com/br3ttb/Arduino-PID-Library for less cycling?

**Comment by vitotai** [comment]
BrewPi has its own PID.
The problem isn't related to PID but the minimum heating time.
I've implemented that, but as an option.

**Comment by tommueller** [comment]
Ah ok, I see.

**Comment by quimnut** [comment]
It settled down a lot for me after the first 2 days, I guess it just needed some time to adjust itself. It still cycles more than my old brewpi setup but much less than when I first reported this.

On my old setup / the arduino brewpi I had to tune Kp/Ki values when I first started to smooth it out (I vaguely recall 4 / 0.1). There is a lot of talk on the brewpi forums about that if you look around re cycling. You can set these with the testcmd.htm page.

Also I have found the best position for chamber sensor is below the fridge element so it reacts more quickly in a large chamber. Likewise I have found a heat band on a SS brew bucket takes longer than HDPE would to heat the wort and can cause some over shooting of heating, where it's heating the stainless so it over shoots a little after it has stopped. Momentum. 

Another experience I can share is when there is a bigger difference in temperature, such as summer, it cycles much less, often only tapping the cooling once every 2-6 hours, but much more when it's say 10-20c.

Overall it's working fine, I do miss the little blue and red lines at the bottom but it's nice and lightweight!

**Comment by vitotai** [comment]
> Overall it's working fine, I do miss the little blue and red lines at the bottom but it's nice and lightweight!


If you are talking about the "heating" and "cooling" color bars under, check the newest code. I just added them.
