### ISSUE TITLE
Support F temp when logging to BrewFather

### ISSUE THREAD

**Issue by dotps1** [vitotai/BrewPiLess#152]
is there anyway to support Fahrenheit temps when sending the data to brewfather.app?

![image](https://user-images.githubusercontent.com/1016996/50127132-c998b680-023d-11e9-9002-6ec7aa55a4fe.png)

basically, because I have Fahrenheit set in brewfather, it just upconverting the Fahrenheit values sent from the brewpiless as if the where Celsius.

thanks!

**Comment by vitotai** [comment]
It seems like brewfather assumes that the temperature values are always in Celsius. BPL just reports the value whatever unit it is.
Let me discuss with Brewfather for this issue.

**Comment by dotps1** [comment]
thanks!  I think you will need some way to signal from bpl what unit it is.  if I have it in C on all systems its fine, but if I have my Brewfather preference set to F, and then have my bpl set to F, it goes F > C > F, so its being sent from bpl as F, then brewfather thinks its C, then upconverts the temp to F again, F > C > F.  hope that makes sense lol.

**Comment by tgangso** [comment]
In version of brewfather 1.4.0 released 21.12.2018. I added a new field to the brewpiless logging format called "tempUnit".

tempUnit can be C for celcius, F for fahrenheit or K for kelvin.

It would be nice if you can add a %variable for that @vitotai and handle it automatically if the user selects Brewfather as logging method.

**Comment by vitotai** [comment]
It will be available in next release., v3.5.
However, the setting must be updated again.

**Comment by tgangso** [comment]
Thank you!

**Comment by dotps1** [comment]
I see 3.5 is released, ill give this a try tonight.

**Comment by dotps1** [comment]
I did try this, but im getting a "not enough free space" error when trying to update the BPL.

**Comment by dotps1** [comment]
I got 3.5 on my BPL, but its still doing the conversion it appears:

![image](https://user-images.githubusercontent.com/1016996/53699221-f035aa80-3db3-11e9-8c7c-dfd5ade48c19.png)

**Comment by dotps1** [comment]
there is also no where on the settings page to put the format string in anymore:

![image](https://user-images.githubusercontent.com/1016996/53699249-486cac80-3db4-11e9-91f8-6029dea667b0.png)

**Comment by dotps1** [comment]
sorry to keep spamming this, but now its 'half way' working.  the actual temps are in F, but the set temps are not:

![image](https://user-images.githubusercontent.com/1016996/53699492-c5008a80-3db6-11e9-9f51-ab49b1987acd.png)

**Comment by Hammersoe** [comment]
Had a quick look at this with the serial output enabled on the BPL. It looks like the BPL sends the units correctly if you have changed it to F instead og C, so the conversion issue might be on the Brewfather end.

Output from a test unit shows that both actual and set temps are sent in F to Brewfather: "{"id":"BPLTEST","beerTemp":76.9,"beerSet":68.0,"fridgeTemp":77.0,"fridgeSet":50.0,"roomTemp":null,"gravity":null,"tiltValue":0.00,"auxTemp":null,"extVolt":null,"timestamp":0,"tempUnit":"F","pressure":null,"mode":"b"}"

@tgangso Are you aware of this still being an issue?
If the units are set to F on BPL, and C on Brewfather the conversation to C only happens on the Temp and not on the Set Temp. If both are set to F then the Temp is reported correctly, but the Set Temp seems to be converted from F to double F.

**Comment by tgangso** [comment]
Thanks for letting me know, I did check my code and you are correct, I am not doing the conversion for the set temps, will fix!

**Comment by dotps1** [comment]
I am closing this, I have verified that all data is reading correctly.  Thanks everyone!  I really appreciate everyones help.  and keep up the good work!
