### ISSUE TITLE
Zero/Negative Setpoints

### ISSUE THREAD

**Issue by jalexandre0** [vitotai/BrewPiLess#16]
If i record well, original/legacy brewpi allow me configure my min/max temps. BrewpiLess don´t let me put zero or negative temperatures and I want to know if it is a bug or some sort of prevention / intended feature.

If is intended, can someone point me i right direction to change it? 

I do my cold crash at -2 ~ -4 range.

**Comment by acremonezi** [comment]
updated link: https://github.com/vitotai/BrewPiLess/wiki/JSON-command
