### ISSUE TITLE
Negative Values at brewchart

### ISSUE THREAD

**Issue by jalexandre0** [vitotai/BrewPiLess#17]
Congrats for amazing work. Likes original brewpi a lot, but have a lot of connection issues with cheap wifi adpaters and Pi back in the day. Nice to see such a powerfull controller on cheap hardware.  

Brewchart goes crazy when beer or freezer setpoing goes nevative. I have a chest freezer and do my cold crash at -2ºC or -4ºC. Depends on ABV. 

I tried to look the issue by myself, but my skills with js/html are very limited at time, and I´m not a programmer. More like a curious guy who handle basic code.  
![negative values](https://user-images.githubusercontent.com/825985/28241277-d6a95962-6967-11e7-9489-848c7c198f80.PNG)

Can you put me on right direction or help me to look at this? 

Thank you.

PS: this is not a real beer, just a profile test for my next batch.

**Comment by vitotai** [comment]
This is a real issue.
I thought that the fermentation temperature would never be lower than zero, Celsius or Fahrenheit. 
Therefore, the code cannot handle negative value. The encoding and decoding of temperature data must be revised to support negative data.

**Comment by zandoga** [comment]
jalexandre0 just use degrees F for now... You won't go negative with F  :)

**Comment by jalexandre0** [comment]
@vitotai  

You are right. Fermentation never should drop about zero, but when cold crashing, you can go the lower you can get without freeze the beer.  

I´ll try to play with it, let me know if you want help or more info.

**Comment by vitotai** [comment]
To save processing power and memory, the data is encoded to use minimum space. 15 bits, to be exact.
Encoding negative values might be possible by adding encoding and decoding of negative data.
One problem remains: what is the maximum and minimum value? 

BTW, you don't get frozen beer at -4C, do you? I though the beer might be frozen under zero.

**Comment by jalexandre0** [comment]
@vitotai 

Is possible to make  Min/Max values dynamic? 

Don´t see a normal setup (fridge, freezer, glycol bank, you name it..)  overshooting min/max inside normal operation, so I guess the tempSetMin and tempSetMax are good enough to charts. 

If not, I simple explaination about how to change hardcoded values are good enough for most of users, I guess. 

You though is not all wrong. I´m not the average brewer.
 
I like to play a lot with Freeze Destilation and high ABV% beers , so I need to freeze  the water on one or other beer to make a high ABV  even HIGHER!!! \;;/ 

But, for normal batchs in normal conditions, you can assume -1ºC (or 0ºC as safer option)  a good to go option for almost everything with some degree of alcohol.

**Comment by vitotai** [comment]
It is of course possible, but not practical. 
What if users set maximum to 120C and minim to -110C? 
To handle such extreme, and sometimes meaningless, situations, the encoding and decoding will be more complicated, and thus buggy.

I am going to do something like -99 ~ 225.  Do you think that's enough?

**Comment by jalexandre0** [comment]
Sounds goog enough. :)

**Comment by jalexandre0** [comment]
Sorry for delay, longer work weeks.

I downloaded and tested new commit, negative values are ok. Thank you for fixing that. 

I guess you can close this issue.
