### ISSUE TITLE
unable to access brewPiLess after going to station mode

### ISSUE THREAD

**Issue by carlosmcmarreiros** [vitotai/BrewPiLess#171]
hi. i flashed the BrewPiLess.v3.5.4m2m.portuguese-br.bin into the wemos d1 mini and everything was working ok. but then i selected the station mode and i cannot access the brewpiless network even i do a fresh flash the network will not show on my wifi conections

**Comment by vitotai** [comment]
In STATION mode, BrewPiLess will only connect to the AP you specified without creating another network. 
The network information is stored in a special section which survives through refresh. You will have to erase that section manually.

**Comment by carlosmcmarreiros** [comment]
thanks for your help everything is ok
