### ISSUE TITLE
multiple iSpindels?

### ISSUE THREAD

**Issue by lekrom** [vitotai/BrewPiLess#172]
Hi Vito,

Just upgraded to latest version, loving it so far. Since I typically run 2 fermentation vessels at a time (my bpl runs a big chest freezer), I was wondering if bpl supports multiple iSpindels? If not, any future plans to do so?

Regards,
Lekrom

**Comment by vitotai** [comment]
I don't think so.
BPL follows the design of original BrewPi which supports ONE fermentation chamber and ONE beer only. Supporting multiple iSpindel doesn't make much sense to me.

**Comment by lekrom** [comment]
Ok. Just a thought...
