### ISSUE TITLE
display LCD not working

### ISSUE THREAD

**Issue by ilaborde** [vitotai/BrewPiLess#178]
Hey, new on BPL, I built the latest code, the temperature sensors are working well, but I can't see any message in the LCD screen, I can see the correct values in the web page.

![IMG_20190530_201533387](https://user-images.githubusercontent.com/2062644/58671298-84160480-8318-11e9-80a3-7f7ecffc12a8.jpg)

Any advice?

**Comment by vitotai** [comment]
http://forum.arduino.cc/index.php?action=dlattach;topic=352362.0;attach=170464

Turn the Potentionmeter to adjust contrast.

**Comment by ilaborde** [comment]
Thans!!
