### ISSUE TITLE
Fridge Temp reports identical values to Beer Temp

### ISSUE THREAD

**Issue by sryburn** [vitotai/BrewPiLess#179]
I have an issue where the Fridge Temp sensor will apparently stop working and fall back to reporting the Beer Temp value for long periods of time. I have sort of confirmed this by unplugging the Fridge Temp sensor and noted that the Fridge Temp reading continues to display the same as Beer Temp. I've also noticed that when I refresh the device list under settings, the fridge temperature sensor does not always display a value.

I naturally assumed a faulty sensor but I have replaced the fridge sensor and there is no change to this behavior. I have also tried erasing EEPROM but this also does not solve the problem. Has anyone else experienced this? Is it expected behavior for the fridge temp to fall back to the beer temp when it can't get a reading? I have an original arduino brewpi which definitely does not behave like this so it seems a bit strange.

![Screenshot from 2019-06-01 15-54-33](https://user-images.githubusercontent.com/4223491/58743629-44225f00-8489-11e9-9213-33381e718939.png)

**Comment by vitotai** [comment]
Check your fridge sensor.

To support Glycol, "fall back sensor" is enabled. The fallback thing is that fridge temp will be from beer sensor when fridge sensor is missing.

Check the wiki for detail:
https://github.com/vitotai/BrewPiLess/wiki/Use-with-Glycol

**Comment by sryburn** [comment]
Thanks @vitotai, the fallback makes sense now! I will try another sensor or maybe disable the settings for glycol support and see what happens.

**Comment by sryburn** [comment]
I have concluded that my temperature sensors work fine by themselves. My issue was resolved by disabling the glycol support settings in `Config.h`, so the simple solution is to only enable glycol support if you actually need it. It still could be something to do with my sensors I guess, eg maybe they don't always return a reading.

**Comment by vitotai** [comment]
That happens.

I had to rewire my sensors,  ditching DIN connectors, to solve this issue.
