### ISSUE TITLE
Improved wiki content for JSON commands

### ISSUE THREAD

**Issue by sryburn** [vitotai/BrewPiLess#180]
Since I just spent some time trying to understand some of these settings, I thought I'd improve the documentation using content found in the original BrewPi project.

Just leaving this here since you can't submit pull requests for the wiki.

[JSON-command.zip](https://github.com/vitotai/BrewPiLess/files/3255918/JSON-command.zip)

**Comment by vitotai** [comment]
Thank a lot.
