### ISSUE TITLE
Failed to Connect to server Controller not updating

### ISSUE THREAD

**Issue by Raoulfonz** [vitotai/BrewPiLess#190]
Hello 
I have spent some time trying to get this working and hope you can point me in the right direction as Im stumped
I was not able to get to 192.168.4.1 on V3.6 thorrak or V3.6v2 thorrak although I can connect to AP. 
I can however connect and config successfully with V3.5thorrak.
Have built Thorrak's board with temp sensor which reads correctly in BPI, and have been stopped by this error as I  cannot seem to find any assistance with that error. Its probably really simple
Any guidance is appreciated.
Thanks - Raoul

![BPIerror](https://user-images.githubusercontent.com/37202256/65383191-d7dbac00-dd54-11e9-880b-09ee4e5c37f5.jpg)

**Comment by quimnut** [comment]
Flash 3.0 or less before the wifi manager changes were added, get it on the network, then upgrade.

**Comment by quimnut** [comment]
I have tz issues on the newer versions using the built in logs, and as the esp can't cope with 2 connections, it dies when someone comes over that has been working on theirs and their phone connects automatically, then complain my wifi is down :)  when they are infact connected to the BPL. The solution to this is run 3.4 where you can have only station mode.

**Comment by vitotai** [comment]
If BPL has connected to a WiFi network before upgrading without change of flash layout. It is exact this behavior that stop me from finding the issue.
The "Auto Reconnect" feature in framework 2.2.0 seems to result in disconnection of AP mode if BPL cannot connect to an AP in AP_STA mode.
The reconnection must be redesign, and the 36v2(well, should be r2, I was in a hurry.) is just a quick solution.

quimnut's advice is valid only when the same flash layout is used, which should be 4m2m.

**Comment by vitotai** [comment]
Update:
I just push a 3.6r3. You might try it.

**Comment by Raoulfonz** [comment]
Thank you for your help
I flashed 3.6r3 version. Now I can get to 192.168.4.1 and behavior is same as version 3.5... so that is now working.... good.
Problem is the behavior is the exactly the same as 3.5, and I am still getting the "failed to connect to server" error as before
![BPIerror2](https://user-images.githubusercontent.com/37202256/65401872-1d0fe480-de0e-11e9-8528-7d917cff062c.jpg)
Here are my flash parameters FYI
![Nodemcu1](https://user-images.githubusercontent.com/37202256/65401914-64967080-de0e-11e9-911e-f7ac884d614b.jpg)
![Nodemcu2](https://user-images.githubusercontent.com/37202256/65401927-737d2300-de0e-11e9-8821-4c935e8919bd.jpg)
I also flashed a new wemos and behavior same.
Thanks for any guidance

**Comment by vitotai** [comment]
If you can use Chrome and open Javascript Console(Alt+Ctrol+J on Mac), under menu "View/Developer options", copy the log for me.

**Comment by Raoulfonz** [comment]
Hope this is what you require:

Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Dygraph.addEvent @ dygraph-combined.js:3
Dygraph.addAndTrackEvent @ dygraph-combined.js:3
t.createDragInterface_ @ dygraph-combined.js:3
t.__init__ @ dygraph-combined.js:2
t @ dygraph-combined.js:2
BrewChart.createChart @ index.htm:1
BrewChart.updateChart @ index.htm:1
i.onload @ index.htm:124
dygraph-combined.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Dygraph.addEvent @ dygraph-combined.js:3
Dygraph.addAndTrackEvent @ dygraph-combined.js:3
t.createDragInterface_ @ dygraph-combined.js:3
t.__init__ @ dygraph-combined.js:2
t @ dygraph-combined.js:2
BrewChart.createChart @ index.htm:1
BrewChart.updateChart @ index.htm:1
i.onload @ index.htm:124
index.htm:124 [Violation] 'load' handler took 152ms

Thanks

**Comment by vitotai** [comment]
Use Chrome from Google. It's available on every platform.
I don't use Firefox and don't have it.

**Comment by lbussy** [comment]
@vitotai if I am understanding this correctly, you need a way to be able to interrupt the auto-connect if there are invalid credentials?

I used a [Double-Reset Detector](https://github.com/jenscski/DoubleResetDetect) (as well as a pin, as well as an application selection ... three is better than one!) to clear the WiFi settings and present the configuration portal.  Actually, I think except for the application-based one I just pop the portal without clearing the config in case it was done in error.

**Comment by Raoulfonz** [comment]
The text above the "Firefox shows this" is from chrome as requested. 
I Just thought I would add that too. sorry for confusion.

**Comment by vitotai** [comment]
Those messages are strange to me.
What I am familiar with is simply the "console", which will show errors if any.
![console](https://user-images.githubusercontent.com/15953213/65569170-31c7b600-df8f-11e9-8b2a-0c9690a9f439.jpg)

**Comment by vitotai** [comment]
> @vitotai if I am understanding this correctly, you need a way to be able to interrupt the auto-connect if there are invalid credentials?
> 
> I used a [Double-Reset Detector](https://github.com/jenscski/DoubleResetDetect) (as well as a pin, as well as an application selection ... three is better than one!) to clear the WiFi settings and present the configuration portal. Actually, I think except for the application-based one I just pop the portal without clearing the config in case it was done in error.

That's a sound suggestion. I've thought of buttons because RESET pin isn't always accessible.

**Comment by Raoulfonz** [comment]
Here is a screenshot. Thanks for you attention and assistance.
![BPI3](https://user-images.githubusercontent.com/37202256/65571374-dd7d0000-dfa7-11e9-964c-fe8f5102c906.jpg)

**Comment by allthepies** [comment]
Sure this isn't a websockets vs SSE config issue ?   i.e. UI using websockets but server (BPL) configured for SSE ?   I had this initially with one version before I found the config compilation directive to enable websockets in BPL.

**Comment by vitotai** [comment]
The log said "Connected", so it should not be SSE/WebSocket issue. (BTW, SSE might not work for now.)

The error messages show ALL three error at the same time, which implies the Javascript couldn't run to certain point. I would guess it's some kind of security setting issue. Th "Violation..." messages also implies that there are some kind of security settings that mine doesn't have.

**Comment by Raoulfonz** [comment]
If it helps the error occurs on my phone or other PC as well.
What do you use to flash with and what are the flashing parameters. Worth investigating?

**Comment by vitotai** [comment]
I use PlatformIO on Mac.
Would you try http://192.168.1.203/testcmd.htm
and capture the screenshot with Javascript Console?

The script somehow stops but the console shows warning that I've never seen.

**Comment by Raoulfonz** [comment]
Here you go
![BPI4](https://user-images.githubusercontent.com/37202256/65650519-a4e43180-e04e-11e9-9cea-9cc9b86ff0bb.jpg)

**Comment by vitotai** [comment]
The connection between the browser and BPL seems fine, but there's something strange.
The message

C{"tempFormat":"C"...}

is sent by demand. It should not be there you if you don't send a "c" character(command).

I don't get it and have no idea why.

Regarding the main page, the "warning" might be the reason or the same cause, but I don't know why they show on your browser but not mine.

**Comment by Raoulfonz** [comment]
I reflashed using a different tool nodemcu pyflasher.
This is in console.
![BPI5](https://user-images.githubusercontent.com/37202256/65661568-4ed6b480-e075-11e9-802b-f0521fdb9e45.jpg)

**Comment by Raoulfonz** [comment]
Here is screenshot
![BPI6](https://user-images.githubusercontent.com/37202256/65734322-b5131400-e115-11e9-93ca-f547a9c72594.jpg)

**Comment by vitotai** [comment]
The BPL controller and web socket connection are working fine. It's just the Javascript doesn't run for some reason.
Maybe you can try another browser.

**Comment by lbussy** [comment]
> If BPL has connected to a WiFi network before upgrading without change of flash layout. It is exact this behavior that stop me from finding the issue.
> The "Auto Reconnect" feature in framework 2.2.0 seems to result in disconnection of AP mode if BPL cannot connect to an AP in AP_STA mode.
> The reconnection must be redesign, and the 36v2(well, should be r2, I was in a hurry.) is just a quick solution.

Okay, I finally hit this, which is described [here](https://github.com/tzapu/WiFiManager/issues/866) I believe.  I don't see much action on it.  Can you explain how you got around it?  I was really hoping not to have to re-write my own libraries. :)

**Comment by Raoulfonz** [comment]
It has same behavior Chrome, Firefox Opera and moble chrome.
and on different PC (windows7.
Interesting error from Firefox:
Source map error: request failed with status 404
Resource URL: http://192.168.1.203/dygraph-combined.js
Source Map URL: dygraph-combined.js.map
It advises to learn more at
https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default.

**Comment by vitotai** [comment]
> > If BPL has connected to a WiFi network before upgrading without change of flash layout. It is exact this behavior that stop me from finding the issue.
> > The "Auto Reconnect" feature in framework 2.2.0 seems to result in disconnection of AP mode if BPL cannot connect to an AP in AP_STA mode.
> > The reconnection must be redesign, and the 36v2(well, should be r2, I was in a hurry.) is just a quick solution.
> 
> Okay, I finally hit this, which is described [here](https://github.com/tzapu/WiFiManager/issues/866) I believe. I don't see much action on it. Can you explain how you got around it? I was really hoping not to have to re-write my own libraries. :)

I check if any saved WiFi network exists by checking WiFi.SSID() at boot up. You can called "wifi_station_get_config()" to get stored SSID instead. If there is no saved network, AP mode is entered without starting STA mode. WiFi.setAutoConnect(false) is called after 5 seconds in connection attempt if it fails. Furthermore, WiFi.begin() seems necessary along with WiFi.setAutoConnect(true) to try reconnect().

I have to admit that I don't really understand how WiFi works from the beginning. For example, the system crashed or didn't work as expected SOMETIMES when changing mode with older version of framework, like two years ago. Adding WiFi.mode(OFF) before change mode seems to solve it or at least reduce the chance of crash. I also found that WiFi behaves differently in different version of framework, like "setAutoConnect()" issue.

**Comment by vitotai** [comment]
> It has same behavior Chrome, Firefox Opera and moble chrome.
> and on different PC (windows7.
> Interesting error from Firefox:
> Source map error: request failed with status 404
> Resource URL: http://192.168.1.203/dygraph-combined.js
> Source Map URL: dygraph-combined.js.map
> It advises to learn more at
> https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default.

No. It's different. There is no such error in all the pictures you provided.

The error is caused by different versions between front-end(HTML/JS) and controller code. You should "REFRESH" to force reload the page.

**Comment by Raoulfonz** [comment]
That is true as I sent only pictures of Chrome as you requested.
When I was checking different browsers, I went into Browser Console. instead of Web Console in Firefox, and that was a new message I saw. I thought it may be of help
Sorry Vito I wont mention Firefox again   :-)
The behavior I referred to was the following error
![BPIerror2](https://user-images.githubusercontent.com/37202256/65813396-318e1b80-e218-11e9-91cc-903a1e827d8f.jpg)
Have refreshed and I get same error on 2 other PCs W7 & W10, and my Android mobile
The one I am on now is W8.1 (hope that helps)

**Comment by vitotai** [comment]
I can't help in you case.

**Comment by lbussy** [comment]
> I check if any saved WiFi network exists by checking WiFi.SSID() at boot up. You can called "wifi_station_get_config()" to get stored SSID instead. If there is no saved network, AP mode is entered without starting STA mode. WiFi.setAutoConnect(false) is called after 5 seconds in connection attempt if it fails. Furthermore, WiFi.begin() seems necessary along with WiFi.setAutoConnect(true) to try reconnect().

At this point, it seems like even if I "ERASE FLASH" I can't get the AP up.  Curiouser and curiouser .  I'll have to make a minimum config and step through it ... again.  :)

**Comment by lbussy** [comment]
@vitotai just an FYI:  I have moved to the "Development" branch of WiFiManager and have not been able to reproduce the original issue I was having.  I know you've already merged/refactored but I thought I'd let you know.

**Comment by Raoulfonz** [comment]
SOLVED
The ESP8266 must be plugged in to circuit board with sensors and then flashed.
I was flashing just ESP8266, then plugging into breakout board.
3.6r3 working well.
