### ISSUE TITLE
[Feature request] Influxdb alt. multiple remote logs

### ISSUE THREAD

**Issue by Naesstrom** [vitotai/BrewPiLess#192]
Would be great to be able to log directly to influxdb to for example create a dashboard in grafana. One way to do it is to use http to write directly to the DB but then we need to be able to add multiple remote logs if we want to use BrewFather or any other service at the same time.

**Comment by quimnut** [comment]
I run it into node-red and go form there.

**Comment by Naesstrom** [comment]
> I run it into node-red and go from there. I push alerts out to pushover too.

Ah smart, I can just use the mqtt flow for that! Want to share your NR flow?
