### ISSUE TITLE
Saving config settings

### ISSUE THREAD

**Issue by RonnyRusten** [vitotai/BrewPiLess#197]
I'm trying to save Configurations, for example Title.
When I hit "Submit Query", the device restarts, and when I reconnect, Title is back to BrewPiLess
Is there anything I'm doing wrong?

**Comment by vitotai** [comment]
What kind of power supply are you using?

**Comment by RonnyRusten** [comment]
I use the USB cable only. I haven't connected it to anything yet, I was just trying to get it to work. If you think I should add a different powersupply, I can try that later today.

**Comment by RonnyRusten** [comment]
I tried connecting a better power supply, but the settings will not stick. After restart (when clicking "Submit Query") all settings are back to default (also wifi). I have ordered a esp8266 and I will try again when it arrives.

**Comment by vitotai** [comment]
Try formatting SPIFFS by
http://[IP of BPL or brewpiless.local:8008/format-spiffs

**Comment by RonnyRusten** [comment]
OK, wil try that when I'm home from work. Thank you.

**Comment by RonnyRusten** [comment]
Hi, again. This did not make any difference. Still not possible to change the title (I haven't tried anything else). Do you have any other tricks I could try, or should I just wait for my new boards? It will probably take a few weeks, ordered them from China (to Norway) a few days ago.

**Comment by vitotai** [comment]
try access the setting directly by 
http://[IP of BPL or brewpiless.local:8008/filemanager
you should find a file name "bpl.cfg".

**Comment by RonnyRusten** [comment]
There are no files on that address, see attached screendump.
![ESP fileviewer](https://user-images.githubusercontent.com/1955294/69014266-bc71d380-0988-11ea-8c6f-c0b1a5ea0860.jpg)

**Comment by RonnyRusten** [comment]
Hi, again.
I'm sorry, I just found out how PlatformIo works...
When I uploaded the env:classic or env:newui tasks, it works as it should.
The "default" tasks seems to be for the d1pro (or something?)
Sorry for being "stupid" (but maybe this should be explained somewhere in the wiki?)
Thank you for trying to help me, I actually learned a few things in the process.

**Comment by vitotai** [comment]
Glad you found the problem.
I constantly change the platform.ini. Therefore, the ability to understand and modify platformio.ini seems to be necessary for those who want to build the project.
