### ISSUE TITLE
Standalone mode

### ISSUE THREAD

**Issue by universam1** [vitotai/BrewPiLess#2]
If the configured wifi network is not reachable, it falls back into WifiManager softAP which is great!

I wonder, would it be possible to serve in this softAP mode the brewPi functionality - so the regular web pages also? 

This would at least give basic functionality (without logging) but would be great if I have my brewing somewhere in the wild without wifi.

Thanks for considering!
Sam

**Comment by vitotai** [comment]
done. There is a "AP mode" now.
