### ISSUE TITLE
Set Original Gravity and Add Gravity Record

### ISSUE THREAD

**Issue by RonnyRusten** [vitotai/BrewPiLess#201]
Is there a bug in the manual gravity input dialogs? If I type in a value, it shows it as a different value at 0C and NaN@.C
See attached image.
(I'm a beer brewing newbie, so there might be a good explanaition to the values...)
![AddGravityRecord](https://user-images.githubusercontent.com/1955294/69502417-60222d00-0f0f-11ea-9adb-26c13a2c0699.jpg)

**Comment by vitotai** [comment]
The first ~ value shows the gravity reading at "calibrating temperature", which can be set in "Gravity" pages.
The seance ~ value shows the gravity reading at current Beer temperature, which seems not available in your case.

**Comment by RonnyRusten** [comment]
Aha, OK. Then it might give more sense when I get my temperature sensors connected, and I will set the calibrating temperature to 20 degrees in the gravity page. Thank you.
