### ISSUE TITLE
Different pins on new SONOFF boards

### ISSUE THREAD

**Issue by anivaldorezende** [vitotai/BrewPiLess#203]
Hi! I'm new in this area, so i need help to assign the right pins to SONOFF, the default pins in the firmware are Sensor on D5, Coolling on D6, but in the newers versions of the SONOFF the D5 are not Available anymore, in the sonoff Mini for example we have the GPIO04 (D2) and not the D5. Have i to compile the code and change the pins on config.h file?

**Comment by vitotai** [comment]
yes. You must edit config.h to change PIN assignment.
