### ISSUE TITLE
Relay issue

### ISSUE THREAD

**Issue by ilaborde** [vitotai/BrewPiLess#219]
Hey I've been trying to make it work my brewpiless, but the relay not responds as expected. I'm not good with electronic, so I've tried with two different relays, thinking that the first one could be broken.  but same issue.
Electricy does not  flow to the sockets. 

Here is my setup: the blue wire, is the electricity and the red one goes to the socket

![IMG_20200225_184746797](https://user-images.githubusercontent.com/2062644/75300747-a0978c80-5817-11ea-920a-87dd1dca5193.jpg)

And my piless config:
![installed working](https://user-images.githubusercontent.com/2062644/75300865-efddbd00-5817-11ea-8f56-d92b81711de8.PNG)

The closest to works well, was with another configuration in the relay, and using "not inverted" option, but when the desired temperature was achieved the relay is still allowing the flow of electricity.

Any advice? 

Thanks in advance & good beers

**Comment by vitotai** [comment]
I am not good at electronics, ether. 
The only advices I could provide are
1. using a multi-meter to check if the PIN, say D5, behaves as expected.
2. checking the RELAY module by providing 3.3V/GND.
I have defected relay modules as other people do.

**Comment by ilaborde** [comment]
could you upload a picture of your wiring please?

**Comment by Hwerow** [comment]
Most relays need the Inverted setting

**Comment by ilaborde** [comment]
Yeah, I've tried, but without success. Tomorrow I'll try with a diff relay, with an additional pin for 5v

**Comment by Naesstrom** [comment]
Can't see much from that image but here's one of my latest build.
![DSC_0130](https://user-images.githubusercontent.com/6575206/75519851-8078f080-5a04-11ea-9a71-e97f9a491f23.JPG)
Brown are the "live wire" and blue is "neutral". from the middle (com) port on the relays they are connected to the heater and cooler and the NO is from the input part.

**Comment by ilaborde** [comment]
Thank you so much, and how do you use your relay? just wired to nodemcu?

**Comment by Naesstrom** [comment]
> Thank you so much, and how do you use your relay? just wired to nodemcu?

yup, followed the instructions here and wired it to D5 and D7
https://github.com/vitotai/BrewPiLess/blob/master/doc/HardwareExample1.md

**Comment by ilaborde** [comment]
It's working, I'm using an old relay,  and I'm providing 5v removing the jumper and is working well.

Thanks so much
