### ISSUE TITLE
How does BPL "PUT" data with GenericHTTP to 3rd-party apps?

### ISSUE THREAD

**Issue by sedgington** [vitotai/BrewPiLess#254]
I've started using a 3rd-party app to control my brewing that only allows "PUT" commands: It has a Data exchange server that listens on a specific URL:Port and then will respond only to "GET" or "PUT" in a JSON format like this: 
[
  {
    "Name": "Fermenter1 rssi",
    "Value": "-70",
    "ValueType": "Value"
  }
  ]
Since I want to incorporate my already built BPL devices into this brewing/fermentation process (and this 3rd-party software does not support iSpindel--which BPL does), I'm looking for a way to "PUT" the data from BPL to the 3rd-party server and fill in the fields I've created there that correspond to the fields you see on "testcmd.htm" on BPL.
Here is what I tried:
Remote logging:
Generic HTTP 
method: PUT
URL: address where the server is listening
Data Type: "application/json"  (I tried it with and without the ")
Format: [{"Name":"sg","Value":"%t","ValueType":"Value"}]
While BPL accepts this, the 3rd-party app does not. If I use the same line as on Format and put it to the server (replacing the %t with a number) using "Advanced Rest Client" the server takes it immediately.
So, I'm having a problem finding what BPL outputs specifically as a JSON format for GenericHTTP and how I should fill out the specific fields above to get it to PUT succesfully. 
Is there a sample template somewhere that would help or a port on BPL that I can "GET" to see the JSON formatting for GenericHTTP? 
If anyone has experience with logging data, whether local, generic http, thingspeak, ubidots, brewfather or brewer's friend and can point me in the right direction for where I'm doing something wrong, that would be tremendously helpful.

;

**Comment by quimnut** [comment]
https://docs.brewfather.app/integrations/brewpiless
I do the above but push it into node-red where i simply wire the http in node to a http out node pointing at brewdad, I I capture all the data locally as well so i can push messages to my phone if temps are unexpected. 

Hope that helps.

**Comment by sedgington** [comment]
Interesting. And so where is node-red running? A local computer/RPI that is always on? If I'm understanding you correctly you are intercepting the data before it goes to Brewfather by giving BPL the URL of where node-red is running, capturing the data and then passing it on to Brewfather. Do you have a flow that you could share? Other than Brewfather not currently (I think) accepting spunding data that would work. Thanks for responding with a good solution so quickly.

**Comment by quimnut** [comment]
It's just 2 nodes wired together to pass through node-red. On the bpl i use http://local_server_ip:1880/ferm1 instead of brewdads url, which is in the request node.

[
    {
        "id": "99ea5577.b2512",
        "type": "http in",
        "z": "922c71ce.c3f99",
        "name": "BrewPiLess1",
        "url": "/ferm1",
        "method": "post",
        "upload": false,
        "swaggerDoc": "",
        "x": 250,
        "y": 460,
        "wires": [
            [
                "895daaa7.1b9d28",
                "807ad908.11f708"
            ]
        ]
    },
    {
        "id": "895daaa7.1b9d28",
        "type": "http request",
        "z": "922c71ce.c3f99",
        "name": "",
        "method": "POST",
        "ret": "obj",
        "paytoqs": "ignore",
        "url": "http://log.brewfather.net/brewpiless?id=redacted",
        "tls": "",
        "persist": false,
        "proxy": "",
        "authType": "",
        "x": 470,
        "y": 460,
        "wires": [
            []
        ]
    },
    {
        "id": "807ad908.11f708",
        "type": "debug",
        "z": "922c71ce.c3f99",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 470,
        "y": 500,
        "wires": []
    }
]

**Comment by sedgington** [comment]
Hey thanks!  I had downloaded node red and played with the "http in" node as per your suggestion and just could not seem to get the data sent over. Once I had your files, I created a new flow based on your import--and still no love. I was going crazy trying to figure out what could be wrong, and started to reply to your post with pictures of my setup--when I realized Vitotai has this fondness for putting slider buttons on the far right side of the page in addition to the "update" button below it. (The same thing I missed initially for quite  a number of visits to the page when trying out the Tilt hydrometer on the new nimble-trial version of BPL.) Bingo! Flipped the switch and data came in! Hopefully your code and this little hint about the button will help someone else! Thanks again!

**Comment by sedgington** [comment]
And...if you create multiple "html in" nodes and rename the respective BPL controllers in the Format section of the "generic HTTP" log Fermenter1, Fermenter2, etc. and wire them up as you did in the example with the single "http in" node, it will pull the data from numerous fermenters and send the data to the fermentation section of the batch that you have attached the device to in Brewfather. Brilliant!
