### ISSUE TITLE
Compile PIO options & iSpindel expiry

### ISSUE THREAD

**Issue by Colin66** [vitotai/BrewPiLess#265]
Hi, when controlling to iSpindel as beer sensor, if that time expires (>5 mins), does control revert to fridge temperature as the next best option until the next iSpindel data ?
I use longer than 900s interval which should still be more than fast enough for a 25l bucket which only changes slowly so plan to increase the timeout in the code.
(I found the PIO config options so edited out that part of the question)
Thanks

**Comment by vitotai** [comment]
NO. 
When Fridge Sensor is missing, reading from Beer Sensor is used. There is no such mechanism when beer sensor is disconnected.
