### ISSUE TITLE
Missing data_log_htm.h

### ISSUE THREAD

**Issue by RaceMouse-of-Denmark** [vitotai/BrewPiLess#27]
Hi,

It seems that data_log_htm.h is missing from the src folder. Has it been added to index/pushed?

//Fink

**Comment by RaceMouse-of-Denmark** [comment]
Hmm...
Same goes for data_gdc_htm.h and data_config_htm.h
//Fink

**Comment by vitotai** [comment]
oops.
I forget to add them to git.

**Comment by RaceMouse-of-Denmark** [comment]
Qapla'
