### ISSUE TITLE
Not able to address others Controller PINs

### ISSUE THREAD

**Issue by acremonezi** [vitotai/BrewPiLess#286]
**Tested on:** ESP-32, 30-PIN
Unable to address other available controller PINs (other than 16, 17, 19, 26 and 27).

**How to reproduce the issue:**

Install the Device & Functions to the specified GPIOs bellow:
- GPIO16 = Chamber Cooler
- GPIO17 = Chamber Heater
- GPIO19 = Chamber Door Switch
- GPIO26 = Chamber Light
- GPIO27 = Chamber Fan

**So, unable to address the following Device & Functions:**

- DHT Humidity Sensor
- Humidifier
- Deumidifier

**Comment by vitotai** [comment]
It's designed intentionally.

Please read through this page: https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

Then, https://github.com/vitotai/BrewPiLess/blob/master/doc/ESP32Pins.md

You should understand the risk of using other free pins. If you want to try, understanding the risks, you can add the PINs by editing
line 202@DeviceManager.h
like
case 5: return 4; // GPIO4
case 6: return 13; // GPIO13

**Comment by acremonezi** [comment]
Thank you very much!
