### ISSUE TITLE
Chamber Door

### ISSUE THREAD

**Issue by acremonezi** [vitotai/BrewPiLess#288]
This is not an issue, it is only a doubt.

**Could you please inform/clarify if the "Chamber Door" actuator has any influence into the BPL logic?**

**Example:** When the Chamber Door is open, is there any software logic that postpone any action such as heater or cooling or something else?

If it is possible and it is easy to say, could you also please inform where can I find this part into the code?

Thank you very much in advanced.

**Comment by vitotai** [comment]
AFAIK, the state of door serves only two purpose:
1. event logging, maybe it might show on the chart of original BrewPi. (But not BPL)
2. light control

you can search, globally, "doorOpen", "isDoorOpen", "doorState", and "door" in the source. There isn't too much code.

I never thought of door even when I ran BrewPiless(legacy) on Arduino.
There are too few pins and I never thought of spare one for door.

**Comment by acremonezi** [comment]
Thank you very much!
