### ISSUE TITLE
Problem with saving devices

### ISSUE THREAD

**Issue by Manhem** [vitotai/BrewPiLess#294]
Hi.
I have tried your new software today and I have got one small problem.
When I shall save devices it does not work.
It's two I2C (DS18S20), heating and cooling.
I choose Device, clear eeprom, Refresh device list, choose Device slot and then press Apply.
This I do on every device. 
After this I try to take a Backup, I only get No installed devices.
If I go to another screen and the back, Refresh device list, nothing has been saved.

It's seems like a lot of thing don't saves.

Any sollution on this problem??

**Comment by vitotai** [comment]
DS18S20 uses OneWire instead of I2C.
You should "Refresh" before "backup".

Not enough information for me on your issue.

**Comment by Manhem** [comment]
Hi.
I'm sorry, my fault.
There was one more thing I have to do that I missed.
Now it works.
