### ISSUE TITLE
Possible to drive remote controlled sockets?

### ISSUE THREAD

**Issue by tommueller** [vitotai/BrewPiLess#31]
Would it be possible to send signals to remote controlled sockets like this: https://www.pollin.de/p/funksteckdosen-set-mit-3-steckdosen-550666

That would be such an easy way to solve the: "I don't mind fiddling with low voltages but am rather scared to connect mainline voltages in self build stuff ..."

Or does anyone know of similiar sockets when allow input of control voltage from the ESP?

Thanks
Tom

**Comment by vitotai** [comment]
NO.
That is RF-based switch. You have to find and install the RF emitter for ESP8266.
The network controlled ones should be better. However, I don't think that is a good idea.
The cost and effort just don't worth it. A hackable SONOFF is a better solution.

**Comment by tommueller** [comment]
Okay I was afraid of that. I bought some multi-outlet power strip that can be turned on/off with power from a USB-port and will check if that also works with 3.3V.
Like this: https://images-na.ssl-images-amazon.com/images/I/31ja-ZhD4OL.jpg
