### ISSUE TITLE
Simple pressure sensor

### ISSUE THREAD

**Issue by neo-64** [vitotai/BrewPiLess#310]
Hi,

Can I use a simple pressure sensor like this one :
https://a.aliexpress.com/_vq9hhV

With esp8266 GPIO15 ? I need a resistor ?

Regards

**Comment by vitotai** [comment]
Yes and No.
The pressure transducer is fine, but 300psi is way too high. The highest pressure tolerance of most container in beer brewing as far as I know is around 60 to 120psi, or lower. Too high maximum would usually result in low resolution.

You can't use GPIO15.

Read the document. 
https://github.com/vitotai/BrewPiLess/blob/master/doc/PressureMonitor.md

**Comment by neo-64** [comment]
this sensor exist in 60psi-5VDC-0.5-4.5V
thanks for the link i'll use external ADS1115  as recomended, maybe one day i would like to automate spunding
