### ISSUE TITLE
Cannot see fourth relay - misidentifying as sensor

### ISSUE THREAD

**Issue by delight-f** [vitotai/BrewPiLess#322]
Thanks so much Vitotai for the great built. I'm using a four-relay board with a built-in esp-12F.

However,under my devices screen it only shows three relays and one sensor device. No sensors are connected. Any ideas why it may be misidentifying a relay as a sensor?

According to the board's schematic, the four relays should be connected via GPIO 12,13 14,16.
[Screenshot](https://user-images.githubusercontent.com/76928118/113471810-4a792c00-94a2-11eb-85ee-159d20aef705.jpg)
[ESP12F_Relay_X4.pdf](https://github.com/vitotai/BrewPiLess/files/6252132/ESP12F_Relay_X4.pdf)

**Comment by delight-f** [comment]
I can't work out how to change the pins in the Config.h file.
It has defined NodeMCU_PIN but on a bare ESP-12F board there are no pin markings!

**Comment by vitotai** [comment]
Forth control pin never exists on ESP8266.
https://github.com/vitotai/BrewPiLess/blob/master/doc/HardwareGeneral.md

**Comment by delight-f** [comment]
> 
> 
> Forth control pin never exists on ESP8266.
> https://github.com/vitotai/BrewPiLess/blob/master/doc/HardwareGeneral.md

I'm confused, because it is identifying a controller pin attached to GPIO 15 - according to my schematic, this IO is connected to ground!

I can therefore only see two control pins connected to relays where I should be able to see three  - please see screenshot.

**Comment by vitotai** [comment]
You should read ALL the code before changing part of it.
Also, read the linked pages in the document provided. 
Last, my D8 works for me.
