### ISSUE TITLE
I2C LCD blank screen

### ISSUE THREAD

**Issue by Hugo-Pereira** [vitotai/BrewPiLess#326]
Hi. I got this I2C LCD https://www.aliexpress.com/item/32991449983.html?spm=a2g0s.9042311.0.0.682a4c4djWkZ2n
I connected everything as per the image provided (https://github.com/vitotai/BrewPiLess/blob/master/doc/image/BPL_simple.jpg), with the exception that I am powering the nodeMCU with USB, and not using any buttons (don't have them).

I was able to read the temperature from the 2 probes, and am also able to control the relay. However, the LCD is blank. It lights up, but doesn't show anything.

I tried to upload esp8266-dev but, although it compiles fine, I get an error when uploading (missing files). I can upload "newui" though. I am not sure if "newui" is the whole firmware? Or should I flash multiple modules like newui + rsp9266-dev? The way I got it working the first time was to just upload all. Some failed, but the device works with the exception of the blank I2C LCD.

I also tried flashing https://github.com/vitotai/BrewPiLess/blob/master/bins/BrewPiLess.v4.1r4.4m2m.bin, and got the same results. Everything works, except for the I2C LCD.

The detected device list is also weird. It detects a lot of devices even with nothing connected.
This is what I get with everything connected:
![image](https://user-images.githubusercontent.com/10086956/115545349-9c3ff580-a29b-11eb-8166-9c8070255a62.png)

I am powering the LCD with 3v3 pin below D4 (as per the image). Tried using the Vin pin, but with same results.

PS: I am a complete novice regarding Arduino and electronics :)
This is the error I get when uploading esp8266-dev

```Retrieving maximum program size .pio\build\esp8266-dev\firmware.elf
Checking size .pio\build\esp8266-dev\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [======    ]  55.7% (used 45620 bytes from 81920 bytes)
Flash: [======    ]  62.8% (used 655424 bytes from 1044464 bytes)
Creating BIN file ".pio\build\esp8266-dev\firmware.bin" using "C:\Users\User Name\.platformio\packages\framework-arduinoespressif8266\bootloaders\eboot\eboot.elf" and ".pio\build\esp8266-dev\firmware.elf"
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Use manually specified: /dev/cu.wchusbserial1410
Uploading .pio\build\esp8266-dev\firmware.bin
esptool.py v2.8
Traceback (most recent call last):
Serial port /dev/cu.wchusbserial1410
  File "C:\Users\User Name\.platformio\packages\tool-esptoolpy\esptool.py", line 3201, in <module>
    _main()
  File "C:\Users\User Name\.platformio\packages\tool-esptoolpy\esptool.py", line 3194, in _main
    main()
  File "C:\Users\User Name\.platformio\packages\tool-esptoolpy\esptool.py", line 2889, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "C:\Users\User Name\.platformio\packages\tool-esptoolpy\esptool.py", line 237, in __init__
    self._port = serial.serial_for_url(port)
  File "C:\Users\User Name\.platformio\penv\lib\site-packages\serial\__init__.py", line 90, in serial_for_url
    instance.open()
  File "C:\Users\User Name\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '/dev/cu.wchusbserial1410': FileNotFoundError(2, 'The system cannot find the path specified.', None, 3)
*** [upload] Error 1
====================================================================================== [FAILED] Took 13.58 seconds ======================================================================================
Environment    Status    Duration
-------------  --------  ------------
esp8266-dev    FAILED    00:00:13.576
================================================================================= 1 failed, 0 succeeded in 00:00:13.576 ================================================================================= 
```

**Comment by stefschin** [comment]
Hi Hugo, this LCD doesn't work with 3.3V, just with 5V. Good luck

**Comment by Hugo-Pereira** [comment]
I powered it with the vin pin also, and it didn't work. Shouldn't it have worked?

**Comment by stefschin** [comment]
Yes, Did you check for contrast? it's a blue potentiometer on the back of I2C LCD

**Comment by Hugo-Pereira** [comment]
Don't really know what that means. This is the back of the device 
![image](https://user-images.githubusercontent.com/10086956/115565727-876e5c80-a2b1-11eb-9865-31c20847db04.png)
