### ISSUE TITLE
Help, abnormal operation in esp32

### ISSUE THREAD

**Issue by jaimeagaviria** [vitotai/BrewPiLess#327]
Hi, I have started brewpiless on an ESP32, the system works for a few hours, but then the display shows strange characters and stops transmitting data to thingspeak.

My configuration is very basic, I have a 5v power supply connected to the vin pin of the nodemcu esp32, the display is also powered from the power supply and not directly from the arduino.

![image](https://user-images.githubusercontent.com/2067106/116089008-08d63e00-a668-11eb-8c53-cbb083116eaa.png)

![image](https://user-images.githubusercontent.com/2067106/116089085-1b507780-a668-11eb-995c-cd5bfde74059.png)

Could you please help me, thank you very much.

**Comment by sdjngyq** [comment]
Please send the picture of the whole circuit to me. I suspect it is caused by the loose contact of your wiring circuit.

**Comment by jaimeagaviria** [comment]
Hello, after some time I have solved this error as follows:

* I have put a 4.7 pull up resistor in the middle of the SDA and 5V pin of the LCD display.

* I have put a 4.7 pull up resistor, in the middle of the SCL pin and 5V of the LCD display.

* I have put a ceramic capacitor in the middle of the 5V and GND pins that connect to the LCD display.

Apparently the problem was caused by electrical noise.

**Comment by sdjngyq** [comment]
OK，congratulations.

**Comment by palmtreefrb** [comment]
> Hello, after some time I have solved this error as follows:
> 
> * I have put a 4.7 pull up resistor in the middle of the SDA and 5V pin of the LCD display.
> * I have put a 4.7 pull up resistor, in the middle of the SCL pin and 5V of the LCD display.
> * I have put a ceramic capacitor in the middle of the 5V and GND pins that connect to the LCD display.
> 
> Apparently the problem was caused by electrical noise.

What capacitor capacitance did you use?

**Comment by jaimeagaviria** [comment]
Hi palmtreefrb.

My underlying problem occurs when the power cables of the lcd display are very close to the power supply of the arduino, I use a 5V 3A supply.

I used a 100uf ceramic capacitor

Kind regards
