### ISSUE TITLE
Default when changing temp manually

### ISSUE THREAD

**Issue by Stolowma** [vitotai/BrewPiLess#329]
When setting the temp with the buttons it always starts at 3.2ºF so if you want to set to say 90º it takes a long time to ramp up. Is there a way to set it to start at a higher value. I looked at the JSON but didn't see anything.

**Comment by vitotai** [comment]
The value should start from the old settings, unless you don't have one. My experience agrees with the code implementation.

**Comment by Stolowma** [comment]
Ahhh, that could be the problem. Thank you.
