### ISSUE TITLE
older html files?

### ISSUE THREAD

**Issue by lekrom** [vitotai/BrewPiLess#34]
Hi Vito,
I noticed that you may have used older html source files in your latest commits. specifically, on the gravity page, the calculate by BPL checkbox is missing. Also, the gravity sensor settings do not seem to stick.

regards, lekrom.

**Comment by vitotai** [comment]
I was off the grid in the last week.
Update the files. Sorry about that.

**Comment by vitotai** [comment]
I am revising the setup.htm. It should be easier to customize the look and feel.
