### ISSUE TITLE
Capping Control not visible on CONTROL Tab with d1MiniPro 16M or d1Mini

### ISSUE THREAD

**Issue by Hwerow** [vitotai/BrewPiLess#340]
Hi Vito,
Thanks for your efforts. I loaded 4.2a5 unmodified bin onto an old d1MiniPro 16M to try out your 4.2 update and noticed that the Capping Control was not visible on the CONTROL Tab. I had Control Pressure selected.
Next, I uploaded 4.1r4 bin to a different d1mini with oled and the same issue. 

Your help appreciated
Cheers

**Comment by vitotai** [comment]
Did you assign a pin for capping control?

**Comment by Hwerow** [comment]
No I did not!  Thankyou for your response.
Cheers
