### ISSUE TITLE
Translated DisplayLcd.cpp and invalid state on index.html page

### ISSUE THREAD

**Issue by petobena** [vitotai/BrewPiLess#354]
Hi @vitotai ,

I have translated strings in DisplayLcd.cpp but now I see only "Invalid state" on index.html page
The strings on Oled LCD are working
Where can be problem?
Thank you

![obrázok](https://user-images.githubusercontent.com/1074366/146656982-306d4e9c-1ebf-4497-8650-5e93d543f274.png)
[DisplayLcd.txt](https://github.com/vitotai/BrewPiLess/files/7740037/DisplayLcd.txt)

**Comment by vitotai** [comment]
The web page parses the displayed string on LCD to get state and time, if any.
The "state", like "waiting to cool", is in fact available for now, but there is no convenient way to get time string.

**Comment by petobena** [comment]
so now is there no way to translate the "state" ?
is there any chance to use strings from locale file in future? make sense to rewrite the code?

**Comment by vitotai** [comment]
Well, it is now done in latest 4.2pre branch. (no pre-built image for now.)
It's what I should've done when I changed classic HTML display.

**Comment by petobena** [comment]
its now perfect, thank you! :)
