### ISSUE TITLE
4.2rc1 ESP32-spiffs and esp32 not recognising pin 23 onewire?

### ISSUE THREAD

**Issue by Hwerow** [vitotai/BrewPiLess#367]
Hi Vito,
I have been trying out 4.2rc1 and I am having a problem in the Device settings. For both the esp32-spiffs and esp32 my temperature probes are not recognised on pin 23.

I then checked with 4.1r4 esp32-oled and pin 23 and the probes were recognised as expected.

Please could you check and advise

Cheers

**Comment by shingle01** [comment]
Hey, I can confirm I have the same issue with the latest push.

**Comment by vitotai** [comment]
It was caused by OneWIre library. I might need to check why the dedicated version must be used. For now, we just use the one that works.
