### ISSUE TITLE
Continuous Reboots when connecting with a mobile device.

### ISSUE THREAD

**Issue by tomohulk** [vitotai/BrewPiLess#369]
For the past few releases, i have not been able to control the bpl device from my iPhone or iPad.  I have tried both Safari and Edge on those devices and i can connect, but after a few second the device reboots.  I do not have this problem from my MacBook Pro, which is also connected via WiFi.  So i am not sure what is happening different from a mobile device, opposed to my laptop.  Its not a huge deal, but i use BrewFather on my iPad when i brew, so it would be nice to set my fermentation temp after i rack it and move it into my chamber all from a single device.

Currently running v4.2

**Comment by vitotai** [comment]
explained in
https://github.com/vitotai/BrewManiacEsp8266/issues/103

It should have been solved.
