### ISSUE TITLE
Glitchy temperature readings

### ISSUE THREAD

**Issue by glenosAU** [vitotai/BrewPiLess#391]
I find I get inconsistent temperature readings from my BrewPiLess. It is like it is dropping data packets, I notice it with the room temp probe (grey line). This then seen to affect the reading for the fridge temp.

It was fine until I rebuilt my set up into a bigger box using three pin connectors for the temp probes. Clearly it seems related to that change. The only difference is the connectors for temp probes and the power supply, instead of a wall plug transformer I have a PSU in the case.

Anyone got a tip on where to look? Or should I rebuild it?

![Screenshot_2021-08-30-20-12-31-42_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/52336530/218006841-22c8a0ac-a503-45f8-9f67-3262d47110b3.jpg)
![IMG20210830201621](https://user-images.githubusercontent.com/52336530/218007302-505fc17f-9170-4e71-976a-a21fc513e37b.jpg)

**Comment by alexlark** [comment]
My money would be on the PSU. I had an unreliable PSU like that style in the past. Now using a RPi PSU.

**Comment by glenosAU** [comment]
Thanks for the suggestion, I'll give it a try when I next brew. Do you
think it would be worthwhile to increase the voltage output to 5.2V or so?

**Comment by alexlark** [comment]
I analysed the output on the PSU with a multimeter and it appeared erratic, +/- 0.5v as such I just didn't trust it, especially adjusting the pot to increase voltage. I assumed that type if PSU may be more suited to LED lights etc. I figured as the RPi PSU was designed for the Pi it would be more stable, the output on the multimeter proved that and it's been rock solid for over 3 years. After using the RPi PSU for a few weeks I stripped it down (the wall wart) so it would fit in my enclosure.

**Comment by quimnut** [comment]
You could try put a 470uF smoothing capacitor across the 5v input.

**Comment by glenosAU** [comment]
Thanks for the suggestions. I was ordering some parts for my coffee machine from mouser and need to spend a bit more for free delivery. So I got one of these.
https://au.mouser.com/ProductDetail/CUI-Inc/PSK-15D-5-T?qs=DRkmTr78QAQphYGnb4sRWQ%3D%3D

Testing so far, 1 hour, shows a lovely stable signal.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
