### ISSUE TITLE
Dedicated additional iSpindel display of SSD1306 OLED LCD - How?

### ISSUE THREAD

**Issue by Justheretoreportanissue** [vitotai/BrewPiLess#397]
Hi!

Maybe I have missed this in the documentation, or I have the wrong interpretation of this added feature of v4.2.
"Dedicated additional iSpindel display of SSD1306 OLED LCD."

How do I wire this additional display up to my NodeMcu ESP8266?

My interpretation is that one now can have 2 OLED displays connected with one providing the normal information and the extra one to only display iSpindel data.

Am I reading this wrong?

Regards,

   /Jonas...

**Comment by vitotai** [comment]
Sorry. I used a wrong word.

I's a specific display designed for iSpindel information.

https://github.com/vitotai/BrewPiLess/blob/master/docs/60.SystemSetup.md

**Comment by Justheretoreportanissue** [comment]
No worries, thanks for responding.

   /Jonas...
