### ISSUE TITLE
Heating/cooling control only with beer sensor

### ISSUE THREAD

**Issue by jacyker** [vitotai/BrewPiLess#408]
Hi 

Beer on kveiks. In this case, it is not about cooling, but about heating. I use a heating belt on the fermenter. The problem is that it doesn't work when there is only a beer sensor (DS18B20 or iSpindel). BPL also requires a "fridge sensor", but with kveiks it is often a shame to block the refrigerator. You can add a second DS18B20 "in the room" and set it as a "fridge", but it would probably be better if in such a situation the BPL simply followed the beer sensor only, with appropriate "caution"?

**Comment by vitotai** [comment]
There is an option, Glycol support. You can use that specific binary.

**Comment by vitotai** [comment]
I just update a new version for making glycol an option, so that you can install all available versions and set the "glycol chilling" configuration in system page.

**Comment by jacyker** [comment]
OK, so only the beer sensor and the "Glycol Chilling" option. Thanks for the info and update :-)

**Comment by jacyker** [comment]
:-)
