### ISSUE TITLE
Beer profile date changes after Apply (in v4.4, esp32 with glycol and pill)

### ISSUE THREAD

**Issue by drbubbles** [vitotai/BrewPiLess#418]
After Applying a Beer Profile, the dates in the profile settings change to ~1970 (but not quite the unix epoch, a bit later).  The profile appears to start correctly, so it is working. Here are before and after screenshots for a simple case.  This is for version 4.4, on an esp32 with glycol enabled, and sensing SG from a pill. 

![image](https://github.com/vitotai/BrewPiLess/assets/6434173/8d456139-e73b-40ea-8bb1-021279416810)

![image](https://github.com/vitotai/BrewPiLess/assets/6434173/367ae0c5-dbcf-4ca6-8261-7c54fd859d4d)

**Comment by vitotai** [comment]
Fixed.
I forgot to convert EPOC time for Javascript Date constructor when loading profile, which is times 1000.
You can upload "control.htm.gz" instead of flashing new image if the fermentation is on going.

**Comment by drbubbles** [comment]
I tried uploading "control.htm.gz" using "restore" in the "System" tab in BrewPiLess, but that must be the wrong way. How do I upload it? (apologies for my ignorance!)

**Comment by vitotai** [comment]
you will need to go to http://[your controller IP]:8008/filemanager

to upload the file.
