### ISSUE TITLE
Cannot Save Anything 

### ISSUE THREAD

**Issue by DindonMaitre** [vitotai/BrewPiLess#426]
Hello, After trying to find a solution and finding nothing, I am turning to you. I cannot save any configuration and I always get error messages. I did click on EEPROM from the beginning, but nothing has changed. Today, I can only use it in the two modes "Fridge Const" or "Beer Const". If you want more information say it . Thank you.

**Comment by vitotai** [comment]
Please check the Document especially FAQ.

**Comment by DindonMaitre** [comment]
I have the solution don't use Brave because you cannot log in. thanks for your time
