### ISSUE TITLE
MQTT configuration.

### ISSUE THREAD

**Issue by raul811** [vitotai/BrewPiLess#432]
I use this application for my fridge and I want to send MQ.T message to my home assistance.
I tried everything to set up the MQT server. But I don't have any topics received in my home assistant..

It is possible to verify the logs for the MQ. TT in the bruises, or how can I do?

**Comment by raul811** [comment]
In the configuration of bru piles, I need to use individual topics or Jason.

I see in the configuration from Homo asdistant U use 304 time and the topic is brupaillas.

Thank you very much for your kind and sorry.If I disturb the the discussion in rather topic I delete it all the message.Thank you again

**Comment by denisfrench** [comment]
![image](https://github.com/user-attachments/assets/80e62949-1633-4d9b-aa74-41b65a4c5f8d)

**Comment by raul811** [comment]
![Screenshot_20241010_133940_Chrome](https://github.com/user-attachments/assets/1135227c-bd10-4a60-b9a7-69a1c323f603)

**Comment by raul811** [comment]
This is my configuration from blue pilots

**Comment by denisfrench** [comment]
You need to toggle the switch next to "Reporting" on.

**Comment by raul811** [comment]
The problem was.I forgot to check the report

Now it's okay and I thank you very much for your help.

**Comment by raul811** [comment]
![Screenshot_20241010_170413_Chrome](https://github.com/user-attachments/assets/7ba438c1-94c5-476a-801d-c992c3713e1f)
![Screenshot_20241010_170502_Home Assistant](https://github.com/user-attachments/assets/2cdbc406-eca7-46f4-b636-6dd4dc0d091f)
