### ISSUE TITLE
ESP32 OLED Does not Work

### ISSUE THREAD

**Issue by lfach** [vitotai/BrewPiLess#445]
I´m using Brewpiless-32 PCB and I cant make OLED to work at all.
I tried to add "Wire.begin(22,23);" on "void setup(void){" as someone here suggested, but still does not work.

Im using ESP32-WROM-32D with Vscode + PlatformIO to compile and upload code to the board. 

I tried with ESP8266 and works like a charm. 

Is there anything else that I forgot?

**Comment by stefschin** [comment]
Hi, as you can see on the [schematic](https://github.com/stefschin/BrewPiLess-32-PCB/blob/master/BPL32%20Schematic%20Rev%2000.pdf) of the board I2C SDA is connected to GPIO 21 and SCL to 22, so it will never work. Anyway you have to be sure how to use the oled display with the firmware, cheers

**Comment by lfach** [comment]
Awesome !!! I was messing up the port numbers....now it worked !!! 
Thanks a lot !!!

**Comment by lfach** [comment]
Is there any way to use bigger TFT screen or even a simple 1.3 pol OLED ?

**Comment by stefschin** [comment]
Sure it's a way to use a bigger OLED but you have to edit the code to make it work, because 1.3 uses another driver.
For TFT you have to change to SPI communication, change driver and design the screens to show and how they behave.

**Comment by stefschin** [comment]
Yes, many but one of the most used I think, it's from [Adafruit](https://learn.adafruit.com/adafruit-gfx-graphics-library/overview)

**Comment by lfach** [comment]
Solution provides worked.
