### ISSUE TITLE
Change HTTP Port

### ISSUE THREAD

**Issue by Makarraum** [vitotai/BrewPiLess#45]
Please, is it possible to add a field in System Config to change HTTP port? It's very usefull to remote access as many routers or internet providers doesn't allow to forward port 80.

Thanks.

**Comment by vitotai** [comment]
Check latest version.

**Comment by Makarraum** [comment]
Thank you very much! Already in the plans for this new version or was it implemented by my request? :D

**Comment by vitotai** [comment]
after you request. It's easy to implement.

**Comment by Makarraum** [comment]
Great! Thanks a lot!

**Comment by Paiakan** [comment]
@Makarraum, I am strugling to make this work, too. How did you do? Which port?
