### ISSUE TITLE
BrewPiLess web stop on "Communicating with BrewPiLess controller"

### ISSUE THREAD

**Issue by diegovazquez** [vitotai/BrewPiLess#51]
hi! i dont have internet in site, and BrewPiLess web won't start.

![brewpiless_problem](https://user-images.githubusercontent.com/3171878/33153826-0205838a-cfc3-11e7-85ec-3bbf608a2428.png)

Thank You

**Comment by vitotai** [comment]
Obviously, you are running BPL in AP mode, aren't you?

The charting library not included. Please read the README. There is a section for it.

You can alternatively use Tom's front-end, which embeds the charting library.
Check:
https://github.com/vitotai/BrewPiLess/issues/21

BTW, did you change the index.htm?
The original index.htm should be HTTP only, like
<script src="http://cdnjs.cloudflare.com/ajax/libs/dygraph/1.1.1/dygraph-combined.js"></script>

**Comment by diegovazquez** [comment]
Yes, i'm running in AP mode, I upload the lib (see photo) and get the same problem.

![brewpiless_problem2](https://user-images.githubusercontent.com/3171878/33182089-4c49cac6-d051-11e7-8b96-4b1ba6c76244.png)

thank you for your help, sorry for my english, is not so good.

Excellent project.

**Comment by vitotai** [comment]
Your index.htm requests https, which should be http. So uploading that lib doesn't work.

You can manually "cache" the library. Connect to internet, and  click the the following url. After your browser got this file, reconnect to BrewPiLess.
https://cdnjs.cloudflare.com/ajax/libs/dygraph/1.1.1/dygraph-combined.js

Alternatively, use Tom's front-end as I have said.

**Comment by diegovazquez** [comment]
thank you,

**Comment by RollyBrewer** [comment]
Strangely, i get this same "Communicating with controller" error on v3rc6, which i believe uses the new front end BUT the error only happens only on my windows laptop. On my MacBook everything is fine, all laptops and BPL are on the same wifi and BPL is in station mode.

Is there some security setting or something per browser maybe?

**Comment by vitotai** [comment]
IE and Edge are not supported.

**Comment by dotps1** [comment]
is there any plans to support IE or Edge?  I am working on setting this up, I hate the idea of needing a secondary browser just to use this webpage.

**Comment by vitotai** [comment]
IE and Edge don't support SSE, or Server Side Event, which is used by BrewPiLess.
WebSocket is a solution. However, the version of AsyncTCP/AsyncWebServer used is not very stable. So, I was forced to sticked with SSE. The latest version seems to be OK, although still not as stable as SSE. Unfortunately, the image will exceed the limit to run on-line update if latest version is used. There are ways. However, I bet a lot of how and why will appear, so I don't jump on them.

**Comment by vitotai** [comment]
If you haven't found it, it is here:
https://github.com/vitotai/BrewPiLess/tree/master/htmljs/dist

**Comment by dotps1** [comment]
Just an FYI, edge now supports SSE it seems

![image](https://user-images.githubusercontent.com/1016996/50127047-6d359700-023d-11e9-88d6-eeea6e4cebc8.png)

Im using edge to configure and monitor now.
