### ISSUE TITLE
BPLv4 Web "LCD" screen not getting updates

### ISSUE THREAD

**Issue by allthepies** [vitotai/BrewPiLess#53]
Just applied BPL v4 to my testbed and the web interface "LCD screen" is not connecting.

Looking at the browser console I see the following error:

![bplerrorv4](https://user-images.githubusercontent.com/1494526/33242623-ed230b94-d2cf-11e7-8751-4dbb68d6b020.JPG)

It would appear that "gotMsg" isn't defined.

Looking in the dist/index.html file I can see gotMsg referenced but not defined.   The variable is defined in the script.js file, within the init_classic() and init() functions but the version of these functions packaged up in the dist/index.html file are missing the variable definition.

Dist file:
`function init_classic(){BChart.init("div_g"),initRssi();onloadCtrl(function(){connBWF(),BChart.start()})}function init(){BChart.init("div_g"),initRssi();connBWF(),BChart.start(),getActiveNavItem()}`

script.js file
`    function init_classic() {
        BChart.init("div_g");
        initRssi();
        var gotMsg = true;
        onloadCtrl(function() {
            connBWF();
            BChart.start();

        });
    }

    function init() {
        BChart.init("div_g");
        initRssi();
        var gotMsg = true;
        connBWF();
        BChart.start();
        getActiveNavItem();
    }`

**Comment by vitotai** [comment]
My fault.
Fixed. Sorry about it.

**Comment by allthepies** [comment]
No problems, thanks for the quick turnaround Vito, all working now.
