### ISSUE TITLE
Calculated by BPL gone

### ISSUE THREAD

**Issue by j0hnsmith** [vitotai/BrewPiLess#54]
In `2.4` the 'Calculated by BPL' option on the gravity config page has gone (btw, still in README.md), so even though I've added the coefficients this request doesn't result in a gravity reading.

```
curl http://brewpiless/gravity -d '{"name":"iSpindel000","ID":3965675,"angle":77.76,"temperature":26.0625,"battery":4.723671,"gravity":0}' -v -H 'Content-Type: application/json'
```
I get a 200 and this timestamp gets updated.
![reading](https://www.dropbox.com/s/tisgr6j11pnw3qs/5c30v46e.png?raw=1)
Also, iSpindel temperature is showing on the chart, but not gravity :cry:

Here's the config I have 
![gravity config](https://www.dropbox.com/s/yfb8sygrwvuiy2g/m9cdd-ij.png?raw=1)

Not sure if this is this expected?

**Comment by vitotai** [comment]
I just fixed it. Please try latest v2.4.2x

**Comment by j0hnsmith** [comment]
@vitotai I'm finally preparing for my next brew but there's no `2.4.2` tag, which commit should I use?

**Comment by j0hnsmith** [comment]
nevermind, found it.

**Comment by j0hnsmith** [comment]
Works, thanks.
