### ISSUE TITLE
Brew and calibrate not working?

### ISSUE THREAD

**Issue by rflemming** [vitotai/BrewPiLess#57]
I can't seem to get ispindel/BPL to work in Brew and Calibrate mode.  The iSpindel is talking to BPL just fine and I can see data coming in:

16:7:33 ↓ G:{"name":"iSpindel001","ID":3514868,"angle":55.30649,"temperature":18.3125,"battery":5.338894,"gravity":15.80349}
16:7:33 ↓ G:{"name":"iSpindel001","battery":5.34,"sg":15.803,"angle":0.00,"lu":1516061252,"lpf":0.10,"stpt":1}
16:9:31 ↓ G:{"name":"iSpindel001","ID":3514868,"angle":55.31021,"temperature":18.3125,"battery":5.338894,"gravity":15.80543}
16:9:31 ↓ G:{"name":"iSpindel001","battery":5.34,"sg":15.805,"angle":0.00,"lu":1516061371,"lpf":0.10,"stpt":1}

When setting up the gravity sensor I selected iSpindel and Calibrate iSpindel and set the tilt in water prior to turning on logging.  Then I enabled local logging and entered the OG and SG which was 1.060 when I started.  I do not see the symbol in the lower right corner of the legend indicating Brew and Calibrate mode.  In addition I see the SG value from the iSpindel being reported in the UI in Plato, and the tilt value is always 0:

![bac](https://user-images.githubusercontent.com/7843512/34966560-8581188c-fa11-11e7-89bf-0250c076431e.png)

Even prior to trying to do Brew and Calibrate the tilt value was never being reported despite it being in the received.  Any help is appreciated.

**Comment by vitotai** [comment]
Read it carefully:
https://github.com/vitotai/BrewPiLess/wiki/Brew-and-Calibrate-iSpindel

I think you at least skip step 5.

**Comment by rflemming** [comment]
If you read my original issue I did those things:

![device](https://user-images.githubusercontent.com/7843512/34971486-b00edaa8-fa2f-11e7-9258-04ba375cad2d.png)

Then setup local logging:

![log](https://user-images.githubusercontent.com/7843512/34971673-e2966b66-fa30-11e7-82fe-41fdd8597210.png)

and recorded OG/SG as 1.060, which I can't screenshot now since the SG is being altered with the value from the iSpindel.

Then I put in the OG/SG.  I've stopped logging and repeated these steps numerous times and still no luck.  Also note that the tilt value is not being reported in the UI despite it being reported by the iSpindel:

20:12:25 ↓ G:{"name":"iSpindel001","ID":3514868,"angle":54.89464,"temperature":18.8125,"battery":5.338894,"gravity":15.58815}

20:12:25 ↓ G:{"name":"iSpindel001","battery":5.34,"sg":15.588,"angle":0.00,"lu":1516075944,"lpf":0.10,"stpt":1}

Note the angle in the first message which I'm assuming comes from the iSpindel iteself, but the angle is absent from the second message which I'm assuming is BPL related.

**Comment by vitotai** [comment]
apologize. I didn't read the text carefully.

That issue should be fixed a few weeks ago. Let me check.

**Comment by rflemming** [comment]
I built the version of 2.4.2 that I'm running from the master branch a few days ago.

**Comment by vitotai** [comment]
Well.
I did NOT fix that bug. Sorry about that.
I just pushed a version 2.4.2x. (Because I am in the progress of v2.5, it takes time for me to change the version number.)

**Comment by rflemming** [comment]
In addition to the 0 tilt issue does that resolve the brew and calibrate problem?

**Comment by vitotai** [comment]
I am not sure about the problem you have.
I brewed with that twice.

**Comment by rflemming** [comment]
I haven't tried it, but I suspect that the Brew and Calibrate issue will be fixed by the solution here: https://github.com/vitotai/BrewPiLess/issues/68
