### ISSUE TITLE
Beer Gravity Input

### ISSUE THREAD

**Issue by Brubrebre** [vitotai/BrewPiLess#6]
Hello,
First of it all, this is such a great project! Props!
Second, I really don´t know if this is the right place to ask that, if not, sorry. It would be awesome if somehow you could input the gravity readings in this. The reading will be manual procedure, but if BrewPiLess could store the information and but it on the chart, will help a lot!
Thank you!

**Comment by vitotai** [comment]
It's already done in the preview branch.
Check it out:
https://github.com/vitotai/BrewPiLess/tree/preview

**Comment by Brubrebre** [comment]
Awesome! I will test it...
Thank you!
