### ISSUE TITLE
Add timezone settings

### ISSUE THREAD

**Issue by mboy-rnd** [vitotai/BrewPiLess#70]
Hello, it would be nice to add a timezone setting, as now the clock shows the wrong time.

**Comment by vitotai** [comment]
https://github.com/vitotai/BrewPiLess/issues/29

**Comment by mboy-rnd** [comment]
In 1264 there is no such expression found in 1487 makeTime(TimeKeeper.getLocalTime Seconds (), t);

**Comment by mboy-rnd** [comment]
Thanks, I figured it out.
