### ISSUE TITLE
Are some *.js scripts missing in htmljs?

### ISSUE THREAD

**Issue by geschwaerzler** [vitotai/BrewPiLess#73]
I'm working on a configuration with 1-wire actors using DS2413. It seems, that device setup has to be augmented for that purpose. When I tried to debug the client code, I discovered some missing files in htmljs:

- htmljs/src/js/script-config.js
- htmljs/src/js/script-gravity.js
- htmljs/src/js/script-logging.js
- htmljs/src/js/script-setup.js

In order to build the client code I might augment gruntfile.coffee as well, isn't it?

Best
Gerhard

**Comment by vitotai** [comment]
Yes. I missed them. Will upload later.

**Comment by vitotai** [comment]
I've uploaded the files. Please check.

**Comment by geschwaerzler** [comment]
sorry, files are still missing. Last commit was on 12th March.

**Comment by vitotai** [comment]
Sorry, I am in the progress of a new feature. Please check this branch:
https://github.com/vitotai/BrewPiLess/tree/AutoCap/htmljs/src

**Comment by geschwaerzler** [comment]
Perfect. And there are other *.js files as well ;-)

I'm going to work with these files and include those that are needed for building the client in a forthcoming pull request.
