### ISSUE TITLE
Can´t save device settings

### ISSUE THREAD

**Issue by h44r3k** [vitotai/BrewPiLess#9]
I´ve just installed latest version of bpl (1.2.7) on a NodeMcu ESP, but i can´t save the device settings.. I apply the changes but when i´m refreshing the device list, it´s back to default settings and devices are unassigned. Anyone else having this problem? Is it possible that mye esp module  isn´t compatible with bpl?

**Comment by vitotai** [comment]
You just need to ERASE the setting and try again.

**Comment by h44r3k** [comment]
Thanks! Now it´s working
