### ISSUE TITLE
loosing wifi after >12h

### ISSUE THREAD

**Issue by LucLN** [vitotai/BrewPiLess#99]
Hi,
I'm usung a NodeMCU V3.1. .. it's working fine, but after half a day it's loosing the wifi-conection.
The buttons and display continue to work.
Does anyone has an idea why this happens or how to fix it ?
It's sitting next to an accespoint.
Thanks.

**Comment by vitotai** [comment]
It might be this issue:
https://github.com/esp8266/Arduino/issues/2750

Under normal operation, it rarely happens. However, it seems that using a notebook which goes to sleep while connecting the BrewPiLess might sometimes run into this issue.
I am looking for a way for it but haven't found one, yet.

**Comment by LucLN** [comment]
ok .. should be this .. I access it with several iOS-devices without closing the browser tab.
On Raspberry Pi zero W's I periodically restart wifi to assure the wlan-connection, maybe this works here to?

**Comment by LucLN** [comment]
yes .. if I close the tab in my browser after visiting BrewPiLess, it's wifi-connection stays open for further contacts :-) Thanks
